### ISSUE TITLE
No VOD on Catch-up channels 

### ISSUE THREAD

**Issue by Rvhalewyn** [add-ons/service.iptv.manager#81] opened 2021-03-22 15:22 UTC
Hi,
Manager works perfectly on Vrtnu and almost perfectly on Flemish commercial TV addons (no EPG on CAZ2, green dots even with no VOD available) . 
I'm aware of CatchUp being very co-operative for implementing, but the add-on has been become  disappointing. Arte and TV5Monde FBS not working, no EPG on Spanish and Italian channels, no VOD from Scheduler on French and French Belgian channels. No login for NPO, so no way to get HD quality for paying viewers. 
It would be great to have direct implementation for Retrospect NPO, Auvio, BBC, German add-on.

**Comment by dagwieers** [comment] 2021-03-22 16:02
@Rvhalewyn Sure, we like to see IPTV Manager adopted more. Please open a feature request for every add-on you like to have IPTV Manager for in the project of that add-on. And then report those tickets at: https://github.com/add-ons/service.iptv.manager/issues/63 so we can track them individually.

The documentation for integrating with IPTV Manager is available from the Wiki: https://github.com/add-ons/service.iptv.manager/wiki/Integration

(This is a duplicate of #63)

**Comment by dagwieers** [comment] 2021-03-22 16:10
For any known problems with add-ons, please open a ticket with the add-on project.

IPTV Manager offers an interface to add-ons for integrating Live channels and EPG/VOD content in the Kodi TV/Radio sections. The channels and content is coming from the add-ons so it requires fixing there.

**Closed** 2021-03-22 17:22 UTC
Labels: duplicate, question
